global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "cy-weather-api"
    static_configs:
      - targets:
          - api:8000

  - job_name: "node_exporter"
    static_configs:
      - targets:
          - host.docker.internal:9100  # Windows / Mac
          # ou localhost:9100 sur Linux
